###服务端口号
#server:
  #port: 8762

spring:
  application:
    ###服务别名
    name: app-bob-eureka

eureka:
  instance:
    ###注册中心IP地址
    hostname: 127.0.0.1
  client:
    service-url:
      ###注册地址
      ###defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/,http://${eureka.instance.hostname}:8763/eureka/
    ###因为自己是注册中心，是否需要将自己注册给自己的注册中心，（集群的时候是需要设置为true）
    register-with-eureka: false
    ###因为自己是注册中心，不需要去检索服务信息
    fetch-registry: false

  server:
    #测试时关闭自我保护机制，保证不可用服务及时剔除
    enable-self-preservation: false
    #间隔2秒剔除一次不可用服务
    evication-interval-timer-in-ms: 2000

